import { SlideFrame } from "@/components/SlideFrame";
import { Card, Callout, Stat, SlideHeader } from "@/components/deck-ui";

/* -------------------- Slide 1 — Title -------------------- */
function S1() {
  return (
    <SlideFrame>
      <div className="flex-1 flex items-center">
        <div className="w-2 h-64 bg-accent rounded-full mr-12 shrink-0" />
        <div className="flex flex-col">
          <h1 className="text-[88px] font-extrabold leading-[1.02] tracking-tight mb-8 max-w-[1600px]">
            Scaling the Shopify App Store
          </h1>
          <p className="text-[36px] text-muted-foreground max-w-[1500px] leading-snug mb-16">
            From <span className="text-foreground font-semibold">45 days to 26 days</span>,
            AI-powered self-review toolkit
          </p>
          <div className="text-[22px] uppercase tracking-[0.22em] text-muted-foreground">
            Mark Tan
          </div>
        </div>
      </div>
    </SlideFrame>
  );
}

/* -------------------- Agenda -------------------- */
function SAgenda() {
  const items = [
    "Business Context",
    "Diagnosing the Bottlenecks",
    "Prioritizing High-Leverage Bets",
    "Deep Dive: AI Review Toolkit",
    "Outcomes and Learnings",
  ];
  return (
    <SlideFrame>
      <SlideHeader kicker="Agenda" title="What we'll cover" />
      <div className="flex flex-col gap-5 flex-1 min-h-0 content-start max-w-[1200px]">
        {items.map((t, i) => (
          <div
            key={t}
            className="flex items-center gap-6 rounded-xl border border-border bg-surface px-8 py-5"
          >
            <span className="font-mono text-[32px] font-bold text-accent shrink-0">
              0{i + 1}
            </span>
            <span className="text-[28px] font-semibold text-foreground">
              {t}
            </span>
          </div>
        ))}
      </div>
    </SlideFrame>
  );
}

/* -------------------- Slide 2 — Business Context -------------------- */
function S2() {
  return (
    <SlideFrame>
      <SlideHeader
        kicker="Business Context"
        title="Scaling Crisis: App Volume Outpaced Our Capacity"
      />
      <div className="grid grid-cols-4 gap-8 mb-10">
        <Stat value="40%" label="spike in app submission volume" tone="accent" />
        <Stat value="45 days" label="SLA at peak (benchmark: 11 days)" tone="negative" />
        <Stat value="23K" label="existing + new developers affected, vocal on social" tone="accent" />
        <Stat value="$1.3B" label="in commerce generated by developers" tone="accent" />
      </div>
      <div className="rounded-xl border-l-4 border-accent bg-accent/10 px-8 py-6">
        <div className="text-accent text-[20px] font-semibold uppercase tracking-[0.18em] mb-2">
          The Problem
        </div>
        <div className="text-[36px] text-foreground leading-snug font-semibold">
          AI lowered the barrier to building apps, causing volume to spike and
          creating ecosystem risk with leadership visibility.
        </div>
      </div>
    </SlideFrame>
  );
}

function SVideo() {
  return (
    <SlideFrame>
      <SlideHeader kicker="Process Walkthrough" title="How App Review works" />
      <div className="flex-1 flex items-center justify-center min-h-0">
        <video
          src="/shopify-app-walkthrough.mp4"
          controls
          className="max-h-full max-w-full rounded-2xl border border-border"
        />
      </div>
    </SlideFrame>
  );
}

/* -------------------- Slide 4 — Role & Mandate -------------------- */
function S3() {
  const leftItems = ["faster approvals", "lower friction", "ecosystem growth"];
  const leftKpis = [
    "Number of apps",
    "Number of developers",
    "SLA (time to review submission)",
  ];
  const rightItems = [
    "merchant trust",
    "fraud prevention",
    "quality standards",
    "platform safety",
  ];
  const rightKpis = [
    "Pass / reject rate",
    "Violations reported post-publish",
    "Reviews and ratings",
  ];
  return (
    <SlideFrame>
      <SlideHeader
        kicker="Role & Mandate"
        title="Mission: Grow the app store without compromising integrity"
      />
      <p className="text-[28px] leading-snug text-muted-foreground mb-8 max-w-[1600px]">
        As Shopify App Store lead, my mandate was to balance two forces in{" "}
        <span className="text-accent font-semibold">direct tension</span>:
      </p>
      <div className="grid grid-cols-[1fr_auto_1fr] items-stretch gap-6 flex-1 min-h-0">
        <div className="rounded-2xl border border-border bg-surface p-10 flex flex-col">
          <div className="text-[40px] font-bold leading-tight mb-6">
            Increase App Volume
          </div>
          <ul className="space-y-3 mb-8">
            {leftItems.map((it) => (
              <li key={it} className="text-[28px] text-muted-foreground flex gap-3">
                <span className="text-accent">·</span>
                <span>{it}</span>
              </li>
            ))}
          </ul>
          <div className="mt-auto pt-6 border-t border-border">
            <div className="text-accent text-[18px] font-semibold uppercase tracking-[0.18em] mb-4">
              Metrics
            </div>
            <ul className="space-y-3">
              {leftKpis.map((it) => (
                <li key={it} className="text-[26px] text-foreground flex gap-3">
                  <span className="text-accent shrink-0">–</span>
                  <span>{it}</span>
                </li>
              ))}
            </ul>
          </div>
        </div>
        <div className="flex items-center text-accent text-[48px] font-bold">
          ⇄
        </div>
        <div className="rounded-2xl border border-border bg-surface p-10 flex flex-col">
          <div className="text-[40px] font-bold leading-tight mb-6">
            Protect Marketplace Integrity
          </div>
          <ul className="space-y-3 mb-8">
            {rightItems.map((it) => (
              <li key={it} className="text-[28px] text-muted-foreground flex gap-3">
                <span className="text-accent">·</span>
                <span>{it}</span>
              </li>
            ))}
          </ul>
          <div className="mt-auto pt-6 border-t border-border">
            <div className="text-accent text-[18px] font-semibold uppercase tracking-[0.18em] mb-4">
              Metrics
            </div>
            <ul className="space-y-3">
              {rightKpis.map((it) => (
                <li key={it} className="text-[26px] text-foreground flex gap-3">
                  <span className="text-accent shrink-0">–</span>
                  <span>{it}</span>
                </li>
              ))}
            </ul>
          </div>
        </div>
      </div>
    </SlideFrame>
  );
}


/* -------------------- Slide 5 — Diagnostic Framework -------------------- */
function SDiagnostic() {
  const steps = [
    "Developer Submission",
    "Pre-Submission Validation",
    "Internal Review Queue",
    "Policy & Compliance Checks",
    "Publish to Store",
  ];
  const bottlenecks = [
    "Poor quality submissions entering queue",
    "Inefficient reviewer routing",
    "Outdated / overlapping requirements",
  ];
  return (
    <SlideFrame>
      <SlideHeader kicker="Diagnostic Framework" title="Where the pipeline broke down" />
      <div className="grid grid-cols-[1.1fr_1fr] gap-12 flex-1 min-h-0">
        <div className="flex flex-col items-center justify-center gap-3">
          {steps.map((label, i) => {
            const width = 100 - i * 8;
            return (
              <div key={label} className="w-full flex flex-col items-center">
                <div
                  className="rounded-lg border border-border flex items-center justify-center px-6 py-5"
                  style={{
                    width: `${width}%`,
                    backgroundColor: `color-mix(in oklab, var(--accent) ${
                      22 - i * 2
                    }%, var(--surface))`,
                  }}
                >
                  <span className="text-accent font-mono text-[20px] mr-4">
                    0{i + 1}
                  </span>
                  <span className="text-[24px] font-semibold text-foreground text-center">
                    {label}
                  </span>
                </div>
                {i < steps.length - 1 && (
                  <div className="text-accent text-[24px] leading-none my-1">↓</div>
                )}
              </div>
            );
          })}
        </div>
        <div className="flex flex-col justify-center">
          <div className="rounded-2xl border border-border bg-[#0b0f1a] p-10">
            <div className="text-accent text-[20px] font-semibold uppercase tracking-[0.18em] mb-6">
              Bottlenecks
            </div>
            <ul className="space-y-5">
              {bottlenecks.map((b) => (
                <li
                  key={b}
                  className="flex gap-4 text-[26px] text-foreground leading-snug"
                >
                  <span className="text-[#ef4444] shrink-0">❌</span>
                  <span>{b}</span>
                </li>
              ))}
            </ul>
          </div>
        </div>
      </div>
    </SlideFrame>
  );
}

/* -------------------- Slide 6 — Ideas We Considered (table) -------------------- */
function S4() {
  const rows: Array<{ name: string; track: string; impact: string; speed: string; complexity: string }> = [
    { name: "Improved submission form", track: "Product / Eng", impact: "Medium", speed: "Fast", complexity: "Low" },
    { name: "AI Self-Review Toolkit", track: "Product / Eng", impact: "High", speed: "Medium", complexity: "Medium" },
    { name: "Frontline SMEs for complex reviews", track: "Ops", impact: "Medium", speed: "Medium", complexity: "Low" },
    { name: "Smart routing by domain expertise", track: "Ops", impact: "Medium", speed: "Medium", complexity: "Low" },
    { name: "Audit 150+ requirements", track: "Governance", impact: "High", speed: "Slow", complexity: "High" },
    { name: "Critical failures → outright rejection", track: "Governance", impact: "High", speed: "Medium", complexity: "Medium" },
  ];
  const tone = (v: string) => {
    if (v === "High" || v === "Fast") return "text-[color:var(--positive)]";
    if (v === "Slow" || v === "High ") return "text-[#ef4444]";
    if (v === "Medium") return "text-[#F59E0B]";
    if (v === "Low") return "text-[color:var(--positive)]";
    return "text-foreground";
  };
  return (
    <SlideFrame>
      <div className="text-accent text-[22px] font-semibold uppercase tracking-[0.2em] mb-4">
        Ideas we considered
      </div>
      <h1 className="text-[60px] font-extrabold leading-[1.05] tracking-tight mb-8">
        We mapped 40+ ideas — here's a subset
      </h1>
      <div className="rounded-2xl border border-border bg-surface overflow-hidden mb-8">
        <div className="grid grid-cols-[2.4fr_1.1fr_1fr_1fr_1fr] gap-6 px-8 py-5 bg-[#0b0f1a] text-[20px] uppercase tracking-[0.16em] text-muted-foreground font-semibold">
          <div>Initiative</div>
          <div>Track</div>
          <div>Impact</div>
          <div>Speed</div>
          <div>Complexity</div>
        </div>
        {rows.map((r, i) => {
          const trackBg: Record<string, string> = {
            "Product / Eng": "color-mix(in oklab, var(--accent) 12%, transparent)",
            "Ops": "color-mix(in oklab, #3B82F6 14%, transparent)",
            "Governance": "color-mix(in oklab, #F59E0B 12%, transparent)",
          };
          return (
            <div
              key={r.name}
              className={`grid grid-cols-[2.4fr_1.1fr_1fr_1fr_1fr] gap-6 px-8 py-5 items-center ${
                i < rows.length - 1 ? "border-b border-border" : ""
              }`}
              style={{ backgroundColor: trackBg[r.track] }}
            >
              <div className="text-[24px] font-semibold text-foreground">{r.name}</div>
              <div className="text-[22px] font-semibold text-foreground">{r.track}</div>
              <div className={`text-[22px] font-semibold ${tone(r.impact)}`}>{r.impact}</div>
              <div className={`text-[22px] font-semibold ${tone(r.speed)}`}>{r.speed}</div>
              <div className={`text-[22px] font-semibold ${tone(r.complexity)}`}>{r.complexity}</div>
            </div>
          );
        })}
      </div>
      <Callout label="Going deeper">
        For this presentation I'll focus on the Product/Eng track — specifically the AI toolkit.
      </Callout>
    </SlideFrame>
  );
}


/* -------------------- Slide 7 — Three Parallel Tracks -------------------- */
function S5() {
  const tracks = [
    {
      title: "Product / Eng",
      accent: "var(--accent)",
      items: [
        "Improved submission form",
        "AI Self-Review Toolkit",
      ],
    },
    {
      title: "Ops",
      accent: "#3B82F6",
      items: [
        "Frontline SMEs for complex reviews",
        "Smart routing by domain expertise",
      ],
    },
    {
      title: "Policy",
      accent: "#F59E0B",
      items: [
        "Audit 150+ requirements",
        "Critical failures → outright rejection",
      ],
    },
  ];
  return (
    <SlideFrame>
      <div className="text-accent text-[22px] font-semibold uppercase tracking-[0.2em] mb-4">
        Ownership Model
      </div>
      <h1 className="text-[60px] font-extrabold leading-[1.05] tracking-tight mb-12">
        Three parallel tracks — Ownership Model
      </h1>
      <div className="grid grid-cols-3 gap-8 mb-8 items-start">
        {tracks.map((t) => (
          <div
            key={t.title}
            className="rounded-2xl border border-border bg-[#0b0f1a] flex flex-col overflow-hidden"
          >
            <div className="h-2" style={{ backgroundColor: t.accent }} />
            <div className="p-8 flex flex-col gap-5">
              <div className="text-[32px] font-bold leading-tight">{t.title}</div>
              <ol className="space-y-4">
                {t.items.map((it, i) => (
                  <li
                    key={it}
                    className="text-[28px] text-foreground leading-snug flex gap-4"
                  >
                    <span className="text-accent font-mono shrink-0">{i + 1}.</span>
                    <span>{it}</span>
                  </li>
                ))}
              </ol>
            </div>
          </div>
        ))}
      </div>
      <Callout label="Going deeper">
        For this presentation I'll focus on the Product/Eng track — specifically
        the AI toolkit.
      </Callout>
    </SlideFrame>
  );
}

/* -------------------- Slide 8 — Improving the Submission Flow -------------------- */
function S6() {
  const cols = [
    {
      title: "The Hypothesis",
      items: [
        "150+ requirements, all feedback via email",
        "One long thread per submission",
        "Back-and-forth until resolved",
      ],
    },
    {
      title: "What We Built & Shipped",
      items: [
        "Replaced email with per-issue checklist",
        "Developers track resolution in portal",
        "Launched as planned",
      ],
    },
    {
      title: "What the Data Showed",
      items: [
        "We reduced wait time from 45 to 40 days (12%)",
        "But developers were still submitting apps without testing",
        "Communication improved, but we need more solution",
      ],
    },
  ];
  return (
    <SlideFrame>
      <SlideHeader title="Improving the submission flow" />
      <div className="grid grid-cols-3 gap-8 mb-8 items-start">
        {cols.map((c, i) => (
          <Card key={c.title} className="flex flex-col">
            <div className="text-accent font-mono text-[24px] mb-3">
              0{i + 1}
            </div>
            <div className="text-[30px] font-bold mb-5 leading-tight">
              {c.title}
            </div>
            <ol className="space-y-4">
              {c.items.map((it, j) => (
                <li
                  key={it}
                  className="text-[26px] text-foreground leading-snug flex gap-3"
                >
                  <span className="text-accent font-mono shrink-0">{j + 1}.</span>
                  <span>{it}</span>
                </li>
              ))}
            </ol>
          </Card>
        ))}
      </div>
      <Callout label="The decision">
        Redirect investment to pre-submission assessment
      </Callout>
    </SlideFrame>
  );
}

/* -------------------- Slide 9 — Shopify AI Self-Review Toolkit -------------------- */
function S7() {
  return (
    <SlideFrame>
      <SlideHeader title="Shopify AI Self-Review Toolkit" />
      <div className="flex flex-col gap-8 flex-1 min-h-0">
        <div className="rounded-2xl border border-border bg-[#0b0f1a] p-10">
          <ul className="space-y-4">
            {[
              "Partnered with QA SMEs who'd reviewed apps manually for years",
              "Taught the system: nuance, edge cases, what a borderline fail looks like",
              "Their input shaped the logic, confidence thresholds, and language",
            ].map((it) => (
              <li
                key={it}
                className="text-[30px] text-foreground leading-snug flex gap-3"
              >
                <span className="text-accent shrink-0">·</span>
                <span>{it}</span>
              </li>
            ))}
          </ul>
        </div>
        <div className="rounded-2xl border border-border bg-[#0b0f1a] p-10">
          <div className="text-accent text-[22px] font-semibold uppercase tracking-[0.18em] mb-5">
            How it works
          </div>
          <ul className="space-y-4">
            {[
              "Runs against developer codebase in ~2 min",
              "Checks all 150+ mechanical compliance requirements",
              "Blocks resubmission until every flagged issue is resolved",
            ].map((it) => (
              <li
                key={it}
                className="text-[30px] text-foreground leading-snug flex gap-3"
              >
                <span className="text-accent shrink-0">·</span>
                <span>{it}</span>
              </li>
            ))}
          </ul>
        </div>
      </div>
    </SlideFrame>
  );
}

/* -------------------- Principle (was S8) -------------------- */
function S8() {
  const groups = [
    { t: "App Developers", d: "23K external developers · vocal on social media" },
    { t: "Governance & Legal", d: "Ecosystem integrity and policy compliance" },
    { t: "Operations / QA", d: "Internal review team conducting manual testing" },
    { t: "Internal Leadership", d: "Directors → VP of Engineering & Product Design" },
  ];
  return (
    <SlideFrame>
      <SlideHeader title="Principle: Shopify Is a Steward, Not Just an Operator" />
      <div className="grid grid-cols-2 gap-10 flex-1 min-h-0">
        <div className="flex flex-col gap-4 justify-center">
          {groups.map((g) => (
            <div
              key={g.t}
              className="flex items-stretch rounded-xl border border-border bg-surface overflow-hidden"
            >
              <div className="w-1.5 bg-accent shrink-0" />
              <div className="px-6 py-5">
                <div className="text-[26px] font-bold leading-tight">{g.t}</div>
                <div className="text-[20px] text-muted-foreground mt-1">{g.d}</div>
              </div>
            </div>
          ))}
        </div>
        <div className="rounded-2xl border border-border bg-[#0b0f1a] p-10 flex flex-col justify-center">
          <div className="text-accent text-[20px] font-semibold uppercase tracking-[0.18em] mb-4">
            Challenges
          </div>
          <ul className="space-y-4">
            {[
              "VP of Eng proposed letting the marketplace self-regulate. On paper: faster SLA, fewer resources. In practice: copycat apps, low-quality submissions, eroded merchant trust.",
              "VP of Product did not support solutions that weren't the source of truth. Example: demo videos or submitting test results.",
              "Director of Ops did not approve partner triage because that meant more complex workflows.",
            ].map((it) => (
              <li
                key={it}
                className="text-[22px] text-muted-foreground leading-snug flex gap-3"
              >
                <span className="text-accent shrink-0">·</span>
                <span>{it}</span>
              </li>
            ))}
          </ul>
          <div className="rounded-xl border-l-4 border-accent bg-accent/10 px-6 py-5 mt-6">
            <div className="text-accent text-[28px] font-semibold leading-snug">
              Short-term wins have long-term consequences.
            </div>
          </div>
        </div>
      </div>
    </SlideFrame>
  );
}

/* -------------------- Outcomes (was S9) -------------------- */
function S9() {
  const rows = [
    { metric: "SLA", before: "45 days", after: "26 days" },
    { metric: "Pass rate", before: "45%", after: "76%" },
    { metric: "AI Toolkit", before: "—", after: "13% adoption at launch" },
    { metric: "Customer Feedback", before: "Escalations", after: "Less surprises on forums/social" },
  ];
  return (
    <SlideFrame>
      <div className="text-accent text-[22px] font-semibold uppercase tracking-[0.2em] mb-4">
        Outcomes
      </div>
      <h1 className="text-[60px] font-extrabold leading-[1.05] tracking-tight mb-10">
        Results across all three tracks
      </h1>
      <div className="flex flex-col gap-6 flex-1 min-h-0">
        <div className="flex items-stretch rounded-2xl border border-border bg-surface overflow-hidden">
          <div className="w-1.5 bg-accent shrink-0" />
          <div className="p-8 flex-1">
            <div className="text-accent text-[20px] font-semibold uppercase tracking-[0.18em] mb-4">
              Product / Eng
            </div>
            <div className="grid grid-cols-[1.2fr_1fr_1.5fr] gap-6 text-[16px] uppercase tracking-[0.16em] text-muted-foreground pb-3 border-b border-border">
              <div>Metric</div>
              <div>Before</div>
              <div>After</div>
            </div>
            {rows.map((r) => (
              <div
                key={r.metric}
                className="grid grid-cols-[1.2fr_1fr_1.5fr] gap-6 py-3 border-b border-border last:border-b-0 items-center"
              >
                <div className="text-[22px] font-semibold text-foreground">
                  {r.metric}
                </div>
                <div className="text-[22px] text-muted-foreground font-mono">
                  {r.before}
                </div>
                <div className="text-[22px] text-[color:var(--positive)] font-semibold">
                  {r.after}
                </div>
              </div>
            ))}
          </div>
        </div>
        <div className="flex items-stretch rounded-2xl border border-border bg-surface overflow-hidden">
          <div className="w-1.5 bg-accent shrink-0" />
          <div className="p-8 flex-1">
            <div className="text-accent text-[20px] font-semibold uppercase tracking-[0.18em] mb-3">
              Ops
            </div>
            <p className="text-[26px] text-muted-foreground leading-snug">
              Frontline ops team built for the most complex submissions — removed
              the bottleneck of generalist reviewers on nuanced cases.
            </p>
          </div>
        </div>
        <div className="flex items-stretch rounded-2xl border border-border bg-surface overflow-hidden">
          <div className="w-1.5 bg-accent shrink-0" />
          <div className="p-8 flex-1">
            <div className="text-accent text-[20px] font-semibold uppercase tracking-[0.18em] mb-3">
              Policy
            </div>
            <p className="text-[26px] text-muted-foreground leading-snug">
              Critical failures category introduced — apps with critical issues
              rejected outright, giving developers clearer signal on what truly
              blocks publication.
            </p>
          </div>
        </div>
      </div>
      <div className="text-[18px] uppercase tracking-[0.2em] text-muted-foreground mt-8">
        Jan → Apr 2026 · 4 months end to end
      </div>
    </SlideFrame>
  );
}

/* -------------------- Slide 13 — Learnings -------------------- */
function S10() {
  const lessons = [
    {
      h: "Define governing principles before generating solutions.",
      d: "In multi-stakeholder environments, principles are a prioritization tool.",
    },
    {
      h: "Ship lean, read the data, then decide where to invest.",
      d: "A lean v1 is a hypothesis test. The data tells you whether to invest more or move on.",
    },
    {
      h: "AI judgment is only as good as the human judgment you embed in it.",
      d: "SME collaboration and human-in-the-loop allow for fine-tuning early products effectively.",
    },
    {
      h: "Parallel workstreams are an ops strategy, not a compromise.",
      d: "Complex operational problems rarely have one root cause. Design for parallel progress, not sequential perfection.",
    },
    {
      h: "Nemawashi (根回し) works wonders.",
      d: "",
    },
  ];
  return (
    <SlideFrame>
      <div className="text-accent text-[22px] font-semibold uppercase tracking-[0.2em] mb-4">
        Learnings
      </div>
      <h1 className="text-[60px] font-extrabold leading-[1.05] tracking-tight mb-10">
        Learnings
      </h1>
      <ol className="flex flex-col gap-5 flex-1 min-h-0">
        {lessons.map((l, i) => (
          <li
            key={i}
            className="rounded-2xl border border-border bg-surface px-8 py-6 flex gap-6"
          >
            <span className="text-accent font-mono text-[32px] font-bold shrink-0">
              {String(i + 1).padStart(2, "0")}
            </span>
            <div>
              <div className="text-[26px] font-bold text-foreground leading-snug">
                {l.h}
              </div>
              {l.d && (
                <div className="text-[22px] text-muted-foreground leading-snug mt-2">
                  {l.d}
                </div>
              )}
            </div>
          </li>
        ))}
      </ol>
    </SlideFrame>
  );
}

/* -------------------- Demo Slide — AI Self-Review Agent -------------------- */
function SDemo() {
  return (
    <SlideFrame>
      <div className="text-accent text-[22px] font-semibold uppercase tracking-[0.2em] mb-4">
        The Solution · Demo
      </div>
      <h1 className="text-[60px] font-extrabold leading-[1.05] tracking-tight mb-10">
        AI self-review agent — here's what it looks like
      </h1>
      <div className="flex-1 flex items-center justify-center min-h-0">
        {/* Terminal mock */}
        <div className="w-full max-w-[1100px] rounded-2xl border border-border bg-[#0b0f1a] overflow-hidden flex flex-col">
          <div className="flex items-center gap-3 px-6 py-4 border-b border-border bg-[#0a0e18]">
            <span className="w-3 h-3 rounded-full bg-[#ff5f56]" />
            <span className="w-3 h-3 rounded-full bg-[#ffbd2e]" />
            <span className="w-3 h-3 rounded-full bg-[#27c93f]" />
            <span className="ml-4 text-muted-foreground font-mono text-[16px]">
              commerce-review · zsh
            </span>
          </div>
          <div className="p-8 font-mono text-[16px] leading-relaxed flex-1">
            <div className="text-foreground">
              <span className="text-accent">$</span> commerce app review --self
            </div>
            <div className="text-muted-foreground mb-5">
              Running compliance checks...
            </div>
            <div className="rounded-xl border border-border bg-[#0a0e18] p-6">
              <div className="text-foreground font-semibold mb-4 text-[18px]">
                Compliance Report
              </div>
              <div className="grid grid-cols-3 gap-4 mb-5">
                <div>
                  <div className="text-[color:var(--positive)] text-[40px] font-bold leading-none">29</div>
                  <div className="text-muted-foreground text-[14px] mt-1">Likely passing</div>
                </div>
                <div>
                  <div className="text-[#F59E0B] text-[40px] font-bold leading-none">3</div>
                  <div className="text-muted-foreground text-[14px] mt-1">Needs review</div>
                </div>
                <div>
                  <div className="text-[#ef4444] text-[40px] font-bold leading-none">1</div>
                  <div className="text-muted-foreground text-[14px] mt-1">Likely failing</div>
                </div>
              </div>
              <div className="space-y-3">
                <div>
                  <div className="text-foreground">
                    <span className="text-[#ef4444] mr-2">x</span>
                    webhooks/orders.create — invalid endpoint
                  </div>
                  <div className="text-muted-foreground text-[13px] ml-6">
                    returns 500 on test payload · recommended fix: verify HMAC
                  </div>
                </div>
                <div>
                  <div className="text-foreground">
                    <span className="text-[#F59E0B] mr-2">?</span>
                    GraphQL version 2023-04 is deprecated
                  </div>
                  <div className="text-muted-foreground text-[13px] ml-6">
                    upgrade to 2024-10 before submission
                  </div>
                </div>
                <div>
                  <div className="text-foreground">
                    <span className="text-[color:var(--positive)] mr-2">✓</span>
                    listing.screenshots — all 5 present, correct dimensions
                  </div>
                  <div className="text-muted-foreground text-[13px] ml-6">
                    1600×900 · PNG
                  </div>
                </div>
                <div>
                  <div className="text-foreground">
                    <span className="text-[color:var(--positive)] mr-2">✓</span>
                    oauth scopes — minimal & justified
                  </div>
                  <div className="text-muted-foreground text-[13px] ml-6">
                    read_products, write_orders
                  </div>
                </div>
              </div>
            </div>
            <div className="text-accent mt-5">$ _</div>
          </div>
        </div>
      </div>
    </SlideFrame>
  );
}

export const commerceSlides = [S1, SAgenda, S2, SVideo, S3, SDiagnostic, S4, S7, SDemo, S9, S8, S10];
