/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WyzeSlideRouteImport } from './routes/wyze.$slide'
import { Route as WorkosSlideRouteImport } from './routes/workos.$slide'
import { Route as CommerceSlideRouteImport } from './routes/commerce.$slide'
import { Route as AboutSlideRouteImport } from './routes/about.$slide'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WyzeSlideRoute = WyzeSlideRouteImport.update({
  id: '/wyze/$slide',
  path: '/wyze/$slide',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkosSlideRoute = WorkosSlideRouteImport.update({
  id: '/workos/$slide',
  path: '/workos/$slide',
  getParentRoute: () => rootRouteImport,
} as any)
const CommerceSlideRoute = CommerceSlideRouteImport.update({
  id: '/commerce/$slide',
  path: '/commerce/$slide',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutSlideRoute = AboutSlideRouteImport.update({
  id: '/about/$slide',
  path: '/about/$slide',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about/$slide': typeof AboutSlideRoute
  '/commerce/$slide': typeof CommerceSlideRoute
  '/workos/$slide': typeof WorkosSlideRoute
  '/wyze/$slide': typeof WyzeSlideRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about/$slide': typeof AboutSlideRoute
  '/commerce/$slide': typeof CommerceSlideRoute
  '/workos/$slide': typeof WorkosSlideRoute
  '/wyze/$slide': typeof WyzeSlideRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about/$slide': typeof AboutSlideRoute
  '/commerce/$slide': typeof CommerceSlideRoute
  '/workos/$slide': typeof WorkosSlideRoute
  '/wyze/$slide': typeof WyzeSlideRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about/$slide'
    | '/commerce/$slide'
    | '/workos/$slide'
    | '/wyze/$slide'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about/$slide'
    | '/commerce/$slide'
    | '/workos/$slide'
    | '/wyze/$slide'
  id:
    | '__root__'
    | '/'
    | '/about/$slide'
    | '/commerce/$slide'
    | '/workos/$slide'
    | '/wyze/$slide'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutSlideRoute: typeof AboutSlideRoute
  CommerceSlideRoute: typeof CommerceSlideRoute
  WorkosSlideRoute: typeof WorkosSlideRoute
  WyzeSlideRoute: typeof WyzeSlideRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wyze/$slide': {
      id: '/wyze/$slide'
      path: '/wyze/$slide'
      fullPath: '/wyze/$slide'
      preLoaderRoute: typeof WyzeSlideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workos/$slide': {
      id: '/workos/$slide'
      path: '/workos/$slide'
      fullPath: '/workos/$slide'
      preLoaderRoute: typeof WorkosSlideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commerce/$slide': {
      id: '/commerce/$slide'
      path: '/commerce/$slide'
      fullPath: '/commerce/$slide'
      preLoaderRoute: typeof CommerceSlideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/$slide': {
      id: '/about/$slide'
      path: '/about/$slide'
      fullPath: '/about/$slide'
      preLoaderRoute: typeof AboutSlideRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutSlideRoute: AboutSlideRoute,
  CommerceSlideRoute: CommerceSlideRoute,
  WorkosSlideRoute: WorkosSlideRoute,
  WyzeSlideRoute: WyzeSlideRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
