/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkosSlideRouteImport } from './routes/workos.$slide'
import { Route as ShopifySlideRouteImport } from './routes/shopify.$slide'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkosSlideRoute = WorkosSlideRouteImport.update({
  id: '/workos/$slide',
  path: '/workos/$slide',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopifySlideRoute = ShopifySlideRouteImport.update({
  id: '/shopify/$slide',
  path: '/shopify/$slide',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/shopify/$slide': typeof ShopifySlideRoute
  '/workos/$slide': typeof WorkosSlideRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/shopify/$slide': typeof ShopifySlideRoute
  '/workos/$slide': typeof WorkosSlideRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/shopify/$slide': typeof ShopifySlideRoute
  '/workos/$slide': typeof WorkosSlideRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/shopify/$slide' | '/workos/$slide'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/shopify/$slide' | '/workos/$slide'
  id: '__root__' | '/' | '/shopify/$slide' | '/workos/$slide'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShopifySlideRoute: typeof ShopifySlideRoute
  WorkosSlideRoute: typeof WorkosSlideRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workos/$slide': {
      id: '/workos/$slide'
      path: '/workos/$slide'
      fullPath: '/workos/$slide'
      preLoaderRoute: typeof WorkosSlideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shopify/$slide': {
      id: '/shopify/$slide'
      path: '/shopify/$slide'
      fullPath: '/shopify/$slide'
      preLoaderRoute: typeof ShopifySlideRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShopifySlideRoute: ShopifySlideRoute,
  WorkosSlideRoute: WorkosSlideRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
